%% Op-Amp with Noise
% 
% This example shows how noise can be incorporated into an electrical
% simulation. The circuit models an amplifier with gain 100 and a
% high-frequency roll off frequency of 10MHz. The op-amp adds noise, and it
% is assumed that the datasheet specifies an equivalent voltage noise
% density of 20nV/Hz^0.5. This is implemented using the noise voltage
% source Vn. Optionally, the thermal noise generated by resistors R1 and R2
% can also be included by selecting 'Enabled' for the blocks' noise mode.
% However, running this model with different combinations of noise sources
% shows that the main source of noise is the equivalent noise voltage.
% 
% 
% 
% 
% 
% 

% Copyright 2008-2023 The MathWorks, Inc.



%% Model

open_system('OpAmpWithNoise')

set_param(find_system('OpAmpWithNoise','FindAll', 'on','type','annotation','Tag','ModelFeatures'),'Interpreter','off')

%% Simulation Results from Spectrum Analyzers

open_system('OpAmpWithNoise/Spectrum Analyzer');
sim('OpAmpWithNoise');

%% 

close_system('OpAmpWithNoise/Spectrum Analyzer');
%%

